const mongoose = require('mongoose');

/**
 * Enhanced Governance Case Schema
 * Unified model for all types of community governance cases
 */
const governanceCaseSchema = new mongoose.Schema({
  // Case identification
  caseId: {
    type: String,
    unique: true,
    required: false,  // Will be auto-generated by pre-save middleware
    index: true
  },
  
  // Case type and metadata
  type: {
    type: String,
    enum: ['CONTENT_REPORT', 'USER_REPORT', 'GUIDELINE_UPDATE', 'FEATURE_REQUEST', 'AI_OVERRIDE'],
    required: true,
    index: true
  },
  title: {
    type: String,
    required: true,
    maxlength: 200
  },
  description: {
    type: String,
    required: true,
    maxlength: 2000
  },
  
  // Case creator
  reporter: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: false,  // Allow null for wallet-only accounts
    index: true
  },
  reporterAddress: {
    type: String,
    required: true,
    lowercase: true,
    index: true
  },
  
  // Case status and timing
  status: {
    type: String,
    enum: ['PENDING_REVIEW', 'ACTIVE_VOTING', 'VOTING_ENDED', 'APPROVED', 'EXECUTED', 'REJECTED', 'APPEALED'],
    default: 'PENDING_REVIEW',
    index: true
  },
  urgency: {
    type: String,
    enum: ['LOW', 'NORMAL', 'HIGH', 'CRITICAL'],
    default: 'NORMAL',
    index: true
  },
  
  // Voting configuration
  votingStartTime: {
    type: Date,
    index: true
  },
  votingEndTime: {
    type: Date,
    index: true
  },
  votingPeriod: {
    type: Number, // minutes (20 mins for testing, normally would be 48 hours = 2880 minutes)
    default: 20
  },

  // Track eligible voters and participation
  eligibleVoters: [{
    walletAddress: {
      type: String,
      lowercase: true
    },
    hasVoted: {
      type: Boolean,
      default: false
    },
    votedAt: Date
  }],
  totalEligibleVoters: {
    type: Number,
    default: 0
  },
  votedCount: {
    type: Number,
    default: 0,
    index: true
  },

  // Voting results
  votes: {
    approve: { type: Number, default: 0 },
    reject: { type: Number, default: 0 }
  },
  totalVotes: {
    type: Number,
    default: 0,
    index: true
  },
  totalVotingWeight: {
    type: Number,
    default: 0
  },
  
  // Execution tracking (enhanced)
  execution: {
    status: {
      type: String,
      enum: ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'REQUIRES_MANUAL'],
      default: 'PENDING'
    },
    executedAt: {
      type: Date
    },
    executedBy: {
      type: String // wallet address or 'SYSTEM'
    },
    actions: [{
      type: {
        type: String,
        enum: [
          'REMOVE_CONTENT', 'HIDE_CONTENT', 'RESTORE_CONTENT', 'FLAG_CONTENT',
          'WARN_USER', 'RESTRICT_USER', 'SUSPEND_USER', 'BAN_USER', 'REMOVE_RESTRICTION',
          'UPDATE_GUIDELINES', 'MODIFY_RULES', 'ADJUST_PARAMETERS',
          'REVERSE_DECISION', 'RESTORE_STATUS'
        ]
      },
      target: String, // ID of target entity
      params: mongoose.Schema.Types.Mixed,
      executedAt: Date,
      result: {
        success: Boolean,
        message: String,
        error: String
      }
    }],
    results: [{
      action: String,
      success: Boolean,
      message: String,
      error: String,
      executedAt: {
        type: Date,
        default: Date.now
      }
    }],
    requiresManualReview: {
      type: Boolean,
      default: false
    },
    manualReviewReason: String,
    error: String,
    retryCount: {
      type: Number,
      default: 0
    }
  },
  
  // Legacy execution fields (maintained for compatibility)
  executed: {
    type: Boolean,
    default: false,
    index: true
  },
  executedAt: {
    type: Date
  },
  executedBy: {
    type: String // wallet address
  },
  executionResult: {
    type: String,
    maxlength: 500
  },
  
  // Case-specific data
  caseData: {
    // Content Appeal specific
    originalContent: {
      postId: { type: mongoose.Schema.Types.Mixed },  // Allow string or ObjectId
      commentId: { type: mongoose.Schema.Types.Mixed },  // Allow string or ObjectId
      contentText: String,
      contentMedia: [String] // IPFS URLs
    },
    
    // AI Moderation override
    aiModerationResult: {
      flagged: Boolean,
      reason: String,
      confidence: Number,
      provider: String,
      timestamp: Date
    },
    
    // User Report specific
    reportedUser: {
      userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      userAddress: String,
      username: String
    },
    violationType: {
      type: String,
      enum: ['HARASSMENT', 'HATE_SPEECH', 'SPAM', 'FRAUD', 'IMPERSONATION', 'OTHER']
    },
    suggestedAction: {
      type: String,
      enum: ['WARNING', 'DELETE_POST', 'TEMP_BAN_48H', 'PERMANENT_BAN'],
      required: false
    },
    
    // Feature Request specific
    featureDetails: {
      category: String,
      priority: String,
      technicalFeasibility: String,
      estimatedEffort: String,
      communityDemand: Number
    },
    
    // Guideline Update specific
    guidelineChange: {
      currentRule: String,
      proposedRule: String,
      rationale: String,
      implementation: String
    }
  },
  
  // Evidence and supporting materials
  evidence: [{
    type: {
      type: String,
      enum: ['SCREENSHOT', 'POST_LINK', 'USER_TESTIMONY', 'PATTERN_ANALYSIS', 'EXTERNAL_LINK', 'OTHER']
    },
    description: String,
    url: String, // IPFS hash or URL
    submittedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    submittedAt: {
      type: Date,
      default: Date.now
    }
  }],
  
  // Related entities
  relatedPosts: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Post'
  }],
  relatedUsers: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  
  // Community discussion
  discussionThread: [{
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    content: {
      type: String,
      required: true,
      maxlength: 1000
    },
    createdAt: {
      type: Date,
      default: Date.now
    },
    upvotes: {
      type: Number,
      default: 0
    },
    downvotes: {
      type: Number,
      default: 0
    }
  }],
  
  // Moderation and quality control
  reviewedBy: [{
    reviewer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    reviewType: {
      type: String,
      enum: ['INITIAL_SCREENING', 'EXPERT_REVIEW', 'COMMUNITY_FEEDBACK']
    },
    decision: String,
    reasoning: String,
    reviewedAt: {
      type: Date,
      default: Date.now
    }
  }],
  
  // Appeal information
  appealable: {
    type: Boolean,
    default: true
  },
  appealDeadline: {
    type: Date
  },
  appeals: [{
    appellant: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    reason: String,
    evidence: String,
    submittedAt: {
      type: Date,
      default: Date.now
    },
    status: {
      type: String,
      enum: ['PENDING', 'APPROVED', 'REJECTED']
    }
  }],
  
  // Metrics and tracking
  metrics: {
    views: { type: Number, default: 0 },
    participationRate: { type: Number, default: 0 },
    controversyScore: { type: Number, default: 0 }, // Based on vote distribution
    communityReach: { type: Number, default: 0 }
  },
  
  // Tags for categorization
  tags: [String],
  
  // Administrative flags
  featured: { type: Boolean, default: false },
  archived: { type: Boolean, default: false },
  sensitive: { type: Boolean, default: false }
  
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Virtual fields
governanceCaseSchema.virtual('isActive').get(function() {
  return this.status === 'ACTIVE_VOTING' && new Date() < this.votingEndTime;
});

governanceCaseSchema.virtual('timeRemaining').get(function() {
  if (!this.isActive) return 0;
  return Math.max(0, this.votingEndTime.getTime() - Date.now());
});

governanceCaseSchema.virtual('participationRate').get(function() {
  if (this.totalVotingWeight === 0) return 0;
  return (this.totalVotes / this.totalVotingWeight) * 100;
});

governanceCaseSchema.virtual('approvalRate').get(function() {
  if (this.totalVotes === 0) return 0;
  return (this.votes.approve / this.totalVotes) * 100;
});

// Indexes for performance
governanceCaseSchema.index({ type: 1, status: 1 });
governanceCaseSchema.index({ votingEndTime: 1, status: 1 });
governanceCaseSchema.index({ urgency: 1, createdAt: -1 });
governanceCaseSchema.index({ 'caseData.reportedUser.userAddress': 1 });
governanceCaseSchema.index({ 'caseData.originalContent.postId': 1 });

// Methods
governanceCaseSchema.methods.canVote = function() {
  return this.status === 'ACTIVE_VOTING' && new Date() < this.votingEndTime;
};

governanceCaseSchema.methods.canExecute = function() {
  // APPROVED and REJECTED are set by the scheduler after voting concludes — always executable
  if (['APPROVED', 'REJECTED'].includes(this.status) && !this.executed) {
    return true;
  }
  // Legacy VOTING_ENDED path (manual admin transition) — still check thresholds
  const majorityThreshold = this.totalVotes * 0.5;
  const quorumThreshold = this.totalVotingWeight * 0.05;
  return this.status === 'VOTING_ENDED' &&
         !this.executed &&
         this.totalVotes >= quorumThreshold &&
         this.votes.approve > majorityThreshold;
};

governanceCaseSchema.methods.generateCaseId = function() {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substr(2, 5);
  return `${this.type}_${timestamp}_${random}`.toUpperCase();
};

// Pre-save middleware
governanceCaseSchema.pre('save', function(next) {
  if (!this.caseId) {
    this.caseId = this.generateCaseId();
  }
  
  // Auto-set voting end time
  if (this.votingStartTime && !this.votingEndTime) {
    this.votingEndTime = new Date(this.votingStartTime.getTime() + (this.votingPeriod * 60 * 60 * 1000));
  }
  
  // Calculate controversy score (higher when votes are split)
  if (this.totalVotes > 0) {
    const approveRate = this.votes.approve / this.totalVotes;
    this.metrics.controversyScore = Math.abs(0.5 - approveRate) * 2; // 0 = most controversial, 1 = unanimous
  }
  
  next();
});

module.exports = mongoose.model('GovernanceCase', governanceCaseSchema);